config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.contact_cart_clear_active 'contact_cart/clear_active',
    :controller => 'contact_carts', :action => 'clear_active', :method => 'get'
  map.resources :contact_carts do |cart|
    cart.remove_contact 'remove_contact',  :controller => 'contact_carts', :action => 'remove_contact',
      :method => 'put'
    cart.make_active 'make_active', :controller => 'contact_carts', :action => 'make_active', 
      :method => 'get'
  end

  map.freemailer_campaign_clear_active 'freemailer_campaigns/clear_active', 
    :controller => 'freemailer_campaigns', :action => 'clear_active', :method => 'get'
  map.resources :freemailer_campaigns  do |campaign|
    campaign.make_active 'make_active', :action => 'make_active', :method => 'get', 
      :controller => 'freemailer_campaigns'
    campaign.send_campaign      'send', :action => 'send_campaign', :method => 'get',
      :controller => 'freemailer_campaigns'
    campaign.statuses       'statuses', :action => 'statuses',
      :controller => 'freemailer_campaigns'
  end

  

  map.root :controller => "/admin/dashboard", :action => :dashboard

  map.resources :contacts
  map.resources :contact_carts
  map.resources :tags
  map.resources :notes
  map.resources :saved_searches

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'

end

app/models/contact_cart.rb
# Holds references to a user who owns the cart, and any number of Contacts belonging to the cart.
#
# At the moment is used by FreemailerCampaignController to build mail campaigns
class ContactCart < ActiveRecord::Base
  belongs_to :user
  has_many :contact_cart_entries, :dependent => :destroy
  has_many :contacts, :through => :contact_cart_entries

  # Provides a list of contacts in the cart joined by ", " or " -- None Added -- " if there are no contacts.
  def contact_names
    contacts.count == 0 ? ' -- None Added -- ' : contacts.map(&:name_for_display).join(', ').squeeze(' ')
  end
  
  # The title of the cart or " -- None Given -- " if absent.
  def title
    self[:title] || ' -- None Given -- '
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def dashboard
  end

  def contacts
  end

  def tags
  end

  def notes
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/shared/dashboard/_contact.html.erb
<li class="item">
<%= check_box_tag 'contact_ids[]', contact.id, false, :class=> 'contact-selector' %> <%= link_to(contact.name_for_display, contact_url(contact) )%>
<% unless contact.primary_email.blank? %>, <%= mail_to(contact.primary_email) %><% end %><br />
  <div class="details" style="display: none;"><%= link_to('edit', edit_contact_url(contact, :_redirect_to => url_for()) ) %> |
    <%= create_compact_object_widget('note',contact,:manage_notes) %>
    <%= create_compact_object_widget('tag',contact,:manage_tags) %>
    <%= h contact.send(display_method) %>
  </div>
</li>

app/views/shared/dashboard/_note.html.erb
<li class="item">
about <%= link_to(note.contact.name_for_display, contact_url(note.contact)) %> &mdash; <em><%= link_to(note.note_excerpt, note_url(note)) %></em><br />
<div class="details" style="display: none;"><strong>from</strong> <%= note.user.username %> <strong>on</strong> <%= h note.send(display_method) %>
    <% unless note.priority.blank? %>
      <strong>Priority:</strong> <%= note.priority %>
    <% end %>
  </div>
</li>

app/views/shared/dashboard/_tag.html.erb
<li class="item">
<span class="tag-display"><span><%= link_to(tag.hierarchical_title, :controller => '/contacts', 'included_tags[]' => tag.id) %></span></span>  on <%= tag.taggings.length %> contacts.<br />
<div class="details" style="display: none;"><%= h tag.send(display_method) %></div>
</li>

app/views/shared/dashboard/_tagging.html.erb
<li class="item">
<span class="tag-display"><span><%= link_to(tagging.tag.hierarchical_title, :controller => '/contacts', 'included_tags[]' => tagging.tag.id) %></span></span> on <%= h tagging.freetaggable.name_for_display %><br />
<div class="details" style="display: none;"><%= h tagging.send(display_method) %></div>
</li>